#!/bin/bash
set -e

pip3 install adafruit-circuitpython-dht

mkdir -p /var/log/temperature

systemctl daemon-reload
systemctl enable temperature-gather.service
systemctl start temperature-gather.service
systemctl enable temperature-upload.timer
systemctl start temperature-upload.timer
systemctl enable temperature-upload.service
systemctl start temperature-upload.service

exit 0