#!/bin/bash
set -e

# TODO: Find a way to install this via apt/control
pip3 install adafruit-circuitpython-dht

mkdir -p /var/log/temperature

systemctl daemon-reload
systemctl enable temperature-gather.service
systemctl restart temperature-gather.service
systemctl enable temperature-upload.timer
systemctl restart temperature-upload.timer
systemctl enable temperature-upload.service
systemctl restart temperature-upload.service

exit 0